#ifndef __fbOsciloskopInfo__
#define __fbOsciloskopInfo__

/**
@file
Subclass of Info, which is generated by wxFormBuilder.
*/

#include "osc.h"

//// end generated include

/** Implementing Info */
class OsciloskopInfo : public Info
{
	protected:
		// Handlers for Info events.
		void ThermalOnActivate( wxActivateEvent& event );
		void InfoOnClose( wxCloseEvent& event );
		void m_textCtrlGlewOnTextURL( wxTextUrlEvent& event );
		void m_buttonOkOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		OsciloskopInfo( wxWindow* parent );
	//// end generated class members

};

#endif // __fbOsciloskopInfo__
