#ifndef __fbOsciloskopHardwareGenerator__
#define __fbOsciloskopHardwareGenerator__

/**
@file
Subclass of HardwareGenerator, which is generated by wxFormBuilder.
*/

#include "osc.h"

//// end generated include

/** Implementing HardwareGenerator */
class OsciloskopHardwareGenerator : public HardwareGenerator
{
	protected:
		// Handlers for HardwareGenerator events.
		void HardwareGeneratorOnInitDialog( wxInitDialogEvent& event );
		void m_comboBoxTypeOnCombobox( wxCommandEvent& event );
		void m_textCtrlFrequencyOnTextEnter( wxCommandEvent& event );
		void m_textCtrlVoltage0OnTextEnter( wxCommandEvent& event );
		void m_spinBtnCh0VoltOnSpinDown( wxSpinEvent& event );
		void m_spinBtnCh0VoltOnSpinUp( wxSpinEvent& event );
		void m_sliderVoltageOnScroll( wxScrollEvent& event );
		void m_textCtrlOffset0OnTextEnter( wxCommandEvent& event );
		void m_spinBtnCh0OffsetOnSpinDown( wxSpinEvent& event );
		void m_spinBtnCh0OffsetOnSpinUp( wxSpinEvent& event );
		void m_sliderOffsetOnScroll( wxScrollEvent& event );
		void m_textCtrlSquareDuty0OnTextEnter( wxCommandEvent& event );
		void m_spinBtnGen0SqrDutyOnSpinDown( wxSpinEvent& event );
		void m_spinBtnGen0SqrDutyOnSpinUp( wxSpinEvent& event );
		void m_sliderSquareDutyOnScroll( wxScrollEvent& event );
		void m_checkBoxSawSlopeOnCheckBox( wxCommandEvent& event );
		void m_filePicker1OnFileChanged( wxFileDirPickerEvent& event );
		void m_buttonCustomFileOnButtonClick( wxCommandEvent& event );
		void m_buttonOn0OnButtonClick( wxCommandEvent& event );
		void m_buttonOff0OnButtonClick( wxCommandEvent& event );
		void m_comboBoxType1OnChoice( wxCommandEvent& event );
		void m_textCtrlFrequency1OnTextEnter( wxCommandEvent& event );
		void m_textCtrlVoltage1OnTextEnter( wxCommandEvent& event );
		void m_spinBtnCh1VoltOnSpinDown( wxSpinEvent& event );
		void m_spinBtnCh1VoltOnSpinUp( wxSpinEvent& event );
		void m_sliderVoltage1OnScroll( wxScrollEvent& event );
		void m_textCtrlOffset1OnTextEnter( wxCommandEvent& event );
		void m_spinBtnCh1OffsetOnSpinDown( wxSpinEvent& event );
		void m_spinBtnCh1OffsetOnSpinUp( wxSpinEvent& event );
		void m_sliderOffset1OnScroll( wxScrollEvent& event );
		void m_textCtrlSquareDuty1OnTextEnter( wxCommandEvent& event );
		void m_spinBtnGen1SqrDutyOnSpinDown( wxSpinEvent& event );
		void m_spinBtnGen1SqrDutyOnSpinUp( wxSpinEvent& event );
		void m_sliderSquareDuty1OnScroll( wxScrollEvent& event );
		void m_checkBoxSawSlope1OnCheckBox( wxCommandEvent& event );
		void m_filePicker11OnFileChanged( wxFileDirPickerEvent& event );
		void m_buttonCustomFile1OnButtonClick( wxCommandEvent& event );
		void m_buttonOn1OnButtonClick( wxCommandEvent& event );
		void m_buttonOff1OnButtonClick( wxCommandEvent& event );
		void m_buttonOkOnButtonClick( wxCommandEvent& event );
		void m_buttonDefaultOnButtonClick( wxCommandEvent& event );
		void m_buttonCancelOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		OsciloskopHardwareGenerator( wxWindow* parent );
	//// end generated class members

};

#endif // __fbOsciloskopHardwareGenerator__
