#ifndef __fbOsciloskopSoftwareGenerator__
#define __fbOsciloskopSoftwareGenerator__

/**
@file
Subclass of SoftwareGenerator, which is generated by wxFormBuilder.
*/

#include "osc.h"

//// end generated include

/** Implementing SoftwareGenerator */
class OsciloskopSoftwareGenerator : public SoftwareGenerator
{
protected:
    // Handlers for SoftwareGenerator events.
    void SoftwareGeneratorOnInitDialog(wxInitDialogEvent& event);
    void m_comboBoxType0OnCombobox(wxCommandEvent& event);
    void m_textCtrlPeriod0OnTextEnter(wxCommandEvent& event);
    void m_comboBoxPeriod0OnCombobox(wxCommandEvent& event);
    void m_textCtrlPeek0OnTextEnter(wxCommandEvent& event);
    void m_comboBoxPeek0OnCombobox(wxCommandEvent& event);
    void m_textCtrlSpeed0OnTextEnter(wxCommandEvent& event);
    void m_textCtrlAvery0OnTextEnter(wxCommandEvent& event);
    void m_buttonOn0OnButtonClick(wxCommandEvent& event);
    void m_buttonOff0OnButtonClick(wxCommandEvent& event);
    void m_comboBoxType1OnCombobox(wxCommandEvent& event);
    void m_textCtrlPeriod1OnTextEnter(wxCommandEvent& event);
    void m_comboBoxPeriod1OnCombobox(wxCommandEvent& event);
    void m_textCtrlPeek1OnTextEnter(wxCommandEvent& event);
    void m_comboBoxPeek1OnCombobox(wxCommandEvent& event);
    void m_textCtrlSpeed1OnTextEnter(wxCommandEvent& event);
    void m_textCtrlAvery1OnTextEnter(wxCommandEvent& event);
    void m_buttonOn1OnButtonClick(wxCommandEvent& event);
    void m_buttonOff1OnButtonClick(wxCommandEvent& event);
    void m_buttonOkOnButtonClick(wxCommandEvent& event);
    void m_buttonDefaultOnButtonClick(wxCommandEvent& event);
    void m_buttonCancelOnButtonClick(wxCommandEvent& event);
public:
    /** Constructor */
    OsciloskopSoftwareGenerator(wxWindow* parent);
    //// end generated class members

};

#endif // __fbOsciloskopSoftwareGenerator__
