#ifndef __fbOsciloskopDebug__
#define __fbOsciloskopDebug__

/**
@file
Subclass of Debug, which is generated by wxFormBuilder.
*/

#include "osc.h"

//// end generated include

/** Implementing Debug */
class OsciloskopDebug : public Debug
{
protected:
    // Handlers for Debug events.
    void ThermalOnActivate(wxActivateEvent& event);
    void m_button561OnButtonClick(wxCommandEvent& event);
    void m_button56OnButtonClick(wxCommandEvent& event);
    void m_button562OnButtonClick(wxCommandEvent& event);
    void m_button5621OnButtonClick(wxCommandEvent& event);
public:
    /** Constructor */
    OsciloskopDebug(wxWindow* parent);
    //// end generated class members

};

#endif // __fbOsciloskopDebug__
