#ifndef __fbOsciloskopDebug__
#define __fbOsciloskopDebug__

/**
@file
Subclass of Debug, which is generated by wxFormBuilder.
*/

#include "osc.h"

//// end generated include

/** Implementing Debug */
class OsciloskopDebug : public Debug
{
	protected:
		// Handlers for Debug events.
		void ThermalOnActivate( wxActivateEvent& event );
		void m_buttonStartOnButtonClick( wxCommandEvent& event );
		void m_buttonStopOnButtonClick( wxCommandEvent& event );
		void m_buttonSaveOnButtonClick( wxCommandEvent& event );
		void m_buttonLuaOnButtonClick( wxCommandEvent& event );
		void m_buttonHelpOnButtonClick( wxCommandEvent& event );
		void m_buttonUploadOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		OsciloskopDebug( wxWindow* parent );
	//// end generated class members




};

#endif // __fbOsciloskopDebug__
