#ifndef __fbOsciloskopMeasure__
#define __fbOsciloskopMeasure__

/**
@file
Subclass of Measure, which is generated by wxFormBuilder.
*/

#include "osc.h"

//// end generated include

/** Implementing Measure */
class OsciloskopMeasure : public Measure
{
	protected:
		// Handlers for Measure events.
		void DisplayOnInitDialog( wxInitDialogEvent& event );
		void m_checkBoxAutoClearOnCheckBox( wxCommandEvent& event );
		void m_checkBoxAutoClearTriggerOnCheckBox( wxCommandEvent& event );
		void m_buttonHistoryClearOnButtonClick( wxCommandEvent& event );
		void m_buttonClearXOnButtonClick( wxCommandEvent& event );
		void m_buttonClearYOnButtonClick( wxCommandEvent& event );
		void m_buttonClearFFTOnButtonClick( wxCommandEvent& event );
		void m_buttonCopyOnButtonClick( wxCommandEvent& event );
		void m_buttonPickX0OnButtonClick( wxCommandEvent& event );
		void m_textCtrlX0OnTextEnter( wxCommandEvent& event );
		void m_spinBtnX0OnSpinDown( wxSpinEvent& event );
		void m_spinBtnX0OnSpinUp( wxSpinEvent& event );
		void m_sliderX0OnScroll( wxScrollEvent& event );
		void m_buttonPickX1OnButtonClick( wxCommandEvent& event );
		void m_textCtrlX1OnTextEnter( wxCommandEvent& event );
		void m_spinBtnX1OnSpinDown( wxSpinEvent& event );
		void m_spinBtnX1OnSpinUp( wxSpinEvent& event );
		void m_sliderX1OnScroll( wxScrollEvent& event );
		void m_buttonPickY0OnButtonClick( wxCommandEvent& event );
		void m_textCtrlY0OnTextEnter( wxCommandEvent& event );
		void m_choiceY0OnChoice( wxCommandEvent& event );
		void m_spinBtnY0OnSpinDown( wxSpinEvent& event );
		void m_spinBtnY0OnSpinUp( wxSpinEvent& event );
		void m_sliderY0OnScroll( wxScrollEvent& event );
		void m_buttonPickY1OnButtonClick( wxCommandEvent& event );
		void m_textCtrlY1OnTextEnter( wxCommandEvent& event );
		void m_choiceY1OnChoice( wxCommandEvent& event );
		void m_spinBtnY1OnSpinDown( wxSpinEvent& event );
		void m_spinBtnY1OnSpinUp( wxSpinEvent& event );
		void m_sliderY1OnScroll( wxScrollEvent& event );
		void m_buttonPickFFT0OnButtonClick( wxCommandEvent& event );
		void m_textCtrlFFT0OnTextEnter( wxCommandEvent& event );
		void m_spinBtnFFT0OnSpinDown( wxSpinEvent& event );
		void m_spinBtnFFT0OnSpinUp( wxSpinEvent& event );
		void m_sliderFFT0OnScroll( wxScrollEvent& event );
		void m_buttonPickFFT1OnButtonClick( wxCommandEvent& event );
		void m_textCtrlFFT1OnTextEnter( wxCommandEvent& event );
		void m_spinBtnFFT1OnSpinDown( wxSpinEvent& event );
		void m_spinBtnFFT1OnSpinUp( wxSpinEvent& event );
		void m_sliderFFT1OnScroll( wxScrollEvent& event );
		void m_SelectionChanged1( wxDataViewEvent& event );
		void m_OnLeftDown( wxMouseEvent& event );
		void m_dataViewListCtrl1OnMouseEvents( wxMouseEvent& event );
		void m_buttonOkOnButtonClick( wxCommandEvent& event );
		void m_buttonDefaultOnButtonClick( wxCommandEvent& event );
		void m_buttonCancelOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		OsciloskopMeasure( wxWindow* parent );
	//// end generated class members

};

#endif // __fbOsciloskopMeasure__
