#define SCOPEFUN_VERSION_MAJOR       "2"
#define SCOPEFUN_VERSION_MINOR       "1"
#define SCOPEFUN_VERSION_MICRO       "1"
#define SCOPEFUN_VERSION_TIMESTAMP   "16:16 06-05-2019"
#define SCOPEFUN_VERSION_TYPE        "not for release"
